name: Deploy frontend app
on:
    push:
        branches: [ master ]
env:
  AZURE_STORAGE_ACCOUNTNAME: le22staticApp  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish and Upload Blazor to static app
      uses: Azure/static-web-apps-deploy@v1
      with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          ###### Repository/Build Configurations
          app_location: './src/frontend/'
          api_location: 'api'
          output_location: './src/frontend/bin/Release/net5.0/wwwroot'
          ###### End of Repository/Build Configurations ######

  # Azure logout 
    - name: logout
      run: |
            az logout
      if: always()