name: Deploy frontend app
on:
    push:
        branches: [ master ]
env:
  AZURE_STORAGE_ACCOUNTNAME: le22staticApp  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301

    - name: Publish Blazor Core Project
      run: dotnet publish ./src/frontend/frontend.csproj -c Release -o output --nologo

    - name: Upload to static app to storage
      uses: Azure/static-web-apps-deploy@v1
      with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          ###### Repository/Build Configurations
          app_location: './src/frontend/'
          api_location: 'api'
          output_location: './output'
          ###### End of Repository/Build Configurations ######

  # Azure logout 
    - name: logout
      run: |
            az logout
      if: always()